global:
  resolve_timeout: 5m

route:
  group_by: [alertname]
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 10s
  receiver: test

receivers:
  - name: test
    webhook_configs:
      - url: http://example.com/
