global:
  # How frequently to scrape targets
  scrape_interval: 10s
  # How frequently to evaluate rules
  evaluation_interval: 10s

rule_files:
  - rules.yaml

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "go_application"
    static_configs:
      - targets: ["host.docker.internal:8080"]
